
export var Material = {
    type:"Material",
    ops:[
        {
            name:"blending",
            text:"blending",
            type:"select",
            des:"混合类型"
        },
        {
            name:"shading",
            text:"shading",
            type:"select",
            des:"阴影类型"
        },
        {
            name:"side",
            text:"side",
            type:"select",
            des:"面显示类型"
        },
        {
            name:"transparent",
            text:"transparent",
            type:"check",
            des:"透明的"
        }
    ]
}
